const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
const FETCH_TRACKS = 'FETCH_TRACKS';
const SELECT_TRACK = 'SELECT_TRACK';


export default { SIGN_IN, SIGN_OUT, FETCH_PLAYLISTS, FETCH_TRACKS, SELECT_TRACK }